# Generated by Django 5.0.2 on 2024-03-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
        ('Auth', '0002_remove_students_id_students_course_students_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.lessons')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.students')),
            ],
        ),
    ]
