# Generated by Django 5.0.2 on 2024-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_alter_internships_starting'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
