# Generated by Django 5.0.2 on 2024-03-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_internships_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cuorse'),
        ),
    ]
